### ISSUE TITLE
Adding new wallpaper don't work

### ISSUE THREAD

**Issue by spruvost** [rocksdanister/system-stats-wallpaper#1]
Hi,

I tried to extract your « Simple.systeme.zip » in a folder « Simple.systeme »  and create an other file « Simple.systeme.zip » with the content of my new folder « Simple.systeme » and add this in lively and lively doesn’t want this new « zip » file.

The content is exacly the same of your « Simple.systeme.zip » file but it doesn’t work.
The new ZIP file is larger than 1Ko and it doesn’t work.

![image](https://user-images.githubusercontent.com/30071389/229337471-6e6631a9-79b9-4179-a1c3-2288cc8bc181.png)

![image](https://user-images.githubusercontent.com/30071389/229337477-97a155de-c860-41e1-a575-0833696170f0.png)

The error message is in french but it’s like : « this is not a lively file »

I don’t know what’s happening ?

**Comment by rocksdanister** [comment]
Share the .zip file.

**Comment by spruvost** [comment]
Le 02/04/2023 09:35 CEST, Dani John ***@***.***> a écrit : 
    
   
       
    
   
       
    
     
   Share the .zip file.

**Comment by spruvost** [comment]
[Simple.System.zip](https://github.com/rocksdanister/system-stats-wallpaper/files/11131620/Simple.System.zip)

**Comment by rocksdanister** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/17554161/229342655-1e95be34-065a-4586-bf73-0736518f0deb.png">

The wallpaper files are inside `Simple.System` folder, the files needs to be in the root of the zip:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/17554161/229342871-a75a4b99-868f-46f3-aa08-1b2c385dcfbd.png">

Do NOT create zip file on your own instead use Lively directly:
After installing the [sample project](https://github.com/rocksdanister/system-stats-wallpaper/releases) on Lively rightclick or press ... -> Open file location and then modify the contents of this folder.
Once complete, rightclick -> Share -> Save to file to produce the .zip file.
