### ISSUE TITLE
Shows integrated GPU instead of dedicated

### ISSUE THREAD

**Issue by luftwafflezz** [rocksdanister/system-stats-wallpaper#2]
This wallpaper shows my integrated gpu stats instead of my dedicated card. I went into settings and changed the graphics settings so that Lively would use my card and restarted Lively but it didn't work.

**Comment by luftwafflezz** [comment]
I tried the steps [here](https://github.com/rocksdanister/lively/wiki/Common-Problems#laptopssystems-with-multiple-gpu) and then restarted my computer but it didn't work.

**Comment by Sawapandeep** [comment]
same problem i changed the app preference from Nvdia control panel as well as from advanced display setting , then restarted Lively but still doesn't work, i even far enough to edit values in script.js , but it stops the whole graphics graph and names it "undefined"

edit, so far i was just able to edit the background only T__T, no progress
![tt](https://github.com/rocksdanister/system-stats-wallpaper/assets/78143025/3158cbe7-f37d-4b1a-87b6-b43718898877)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/1508

**Comment by luftwafflezz** [comment]
> same problem i changed the app preference from Nvdia control panel as well as from advanced display setting , then restarted Lively but still doesn't work, i even far enough to edit values in script.js , but it stops the whole graphics graph and names it "undefined"
> 
> edit, so far i was just able to edit the background only T__T, no progress ![tt](https://private-user-images.githubusercontent.com/78143025/247814445-3158cbe7-f37d-4b1a-87b6-b43718898877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTM1MzEsIm5iZiI6MTcxNjgxMzIzMSwicGF0aCI6Ii83ODE0MzAyNS8yNDc4MTQ0NDUtMzE1OGNiZTctZjM3ZC00YjFhLTg3YjYtYjQzNzE4ODk4ODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMzE1YjA0OWVmY2Y0MjZjZTdjNTk4ZjMyOWQ3Yjc0ZWNhMGU3YzBkOWMwYjgzY2ExZjEyZGZiYjlhYTYyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoTLD5mF4xWGhSew60niqiFclIzUf7vcxlAPZPtUn9s)

Does your GPU support encoding? I have a crappy discrete AMD GPU (RX 6400 to be exact), and it doesn't support encoding, which means that lively won't use it, so I think that has something to do with it.

**Comment by Sawapandeep** [comment]
> > same problem i changed the app preference from Nvdia control panel as well as from advanced display setting , then restarted Lively but still doesn't work, i even far enough to edit values in script.js , but it stops the whole graphics graph and names it "undefined"
> > edit, so far i was just able to edit the background only T__T, no progress ![tt](https://private-user-images.githubusercontent.com/78143025/247814445-3158cbe7-f37d-4b1a-87b6-b43718898877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTM1MzEsIm5iZiI6MTcxNjgxMzIzMSwicGF0aCI6Ii83ODE0MzAyNS8yNDc4MTQ0NDUtMzE1OGNiZTctZjM3ZC00YjFhLTg3YjYtYjQzNzE4ODk4ODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMzE1YjA0OWVmY2Y0MjZjZTdjNTk4ZjMyOWQ3Yjc0ZWNhMGU3YzBkOWMwYjgzY2ExZjEyZGZiYjlhYTYyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoTLD5mF4xWGhSew60niqiFclIzUf7vcxlAPZPtUn9s)
> 
> Does your GPU support encoding? I have a crappy discrete AMD GPU (RX 6400 to be exact), and it doesn't support encoding, which means that lively won't use it, so I think that has something to do with it.
 Mine is GTX 1650 so it probably has that  NVENC by Nvidia, what i think is that we cant tinker in mobile GPUs(my case) , this lively wallpaper works well on my PC , but for some reason is buggy on laptops, maybe because of vendor/OEM security reasons.
